# -*- coding: utf-8 -*-
"""Student_Gradebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mf6U-JM5DhsXKZZnjVtQYV1CvWtHVUn_
"""

gradebook = {}

def add_student():
    name = input("Enter student name: ")
    if name in gradebook:
        print("Student already exists.")
    else:
        gradebook[name] = []
        print(f"{name} added to gradebook.")

def add_grade():
    name = input("Enter student name to add grade: ")
    if name not in gradebook:
        print("Student not found.")
        return
    try:
        grade = float(input(f"Enter grade for {name}: "))
        gradebook[name].append(grade)
        print(f"Grade {grade} added for {name}.")
    except ValueError:
        print("Invalid grade. Please enter a number.")

def view_grades():
    name = input("Enter student name to view grades: ")
    if name not in gradebook:
        print("Student not found.")
        return

    grades = gradebook[name]
    if not grades:
        print(f"{name} has no grades yet.")
    else:
        print(f"Grades for {name}: {grades}")
        average = sum(grades) / len(grades)
        print(f"Average grade for {name}: {average:.2f}")

def view_all_students():
    if not gradebook:
        print("No students in gradebook.")
        return

    print("\n--- All Students ---")
    for name, grades in gradebook.items():
        if grades:
            average = sum(grades) / len(grades)
            print(f"{name} -> Grades: {grades}, Average: {average:.2f}")
        else:
            print(f"{name} -> No grades available")

def main_gradebook_menu():
    while True:
        print("\n====== STUDENT GRADEBOOK ======")
        print("1. Add Student")
        print("2. Add Grade")
        print("3. View Grades and Average")
        print("4. Exit")
        print("5. View All Students")

        choice = input("Enter your choice: ")

        if choice == '1':
            add_student()
        elif choice == '2':
            add_grade()
        elif choice == '3':
            view_grades()
        elif choice == '4':
            print("Exiting Gradebook. Goodbye!")
            break
        elif choice == '5':
            view_all_students()
        else:
            print("Invalid choice. Please try again.")

main_gradebook_menu()